services:
  web:
    build:
      context: .
      dockerfile: Magnise.Web/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://localhost:5000/
      - DbConnection=Server=host.docker.internal;Database=MagniseAssets;Integrated Security=True;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"